### ISSUE TITLE
`parser.arguments(&["-x", "c++"])` works, `.arguments(&["-x c++"])` does not 

### ISSUE THREAD

**Issue by PatriceJiang** [KyleMayes/clang-rs#18]
I expected these two methods should be equivalent

**Comment by KyleMayes** [comment]
Sorry for leaving this open for so long.

I have closed the pull request and this issue because this is the expected behavior. On some platforms, namely Windows, it is not unusual to have spaces in filenames, so `&["My Source Code.hpp"]` cannot be mapped to `&["My", "Source", "Code.hpp"]` without breaking things.
