### ISSUE TITLE
libclang is not loaded while having bindgen as dependency

### ISSUE THREAD

**Issue by LastLightSith** [KyleMayes/clang-rs#40]
This works

Cargo.toml:-
```toml
[package]
name = "bindgen_with_clang"
version = "0.1.0"
edition = "2018"

[build-dependencies]
#bindgen = "0.57.0" #uncommenting this panics the build.rs
clang = "1.0.3"
```

build.rs:-
```rust
use clang::*;

fn main() {
    let clang = Clang::new().unwrap();
    let index = Index::new(&clang, false, false);
    let tu = index.parser("test.hpp").parse().unwrap();
}
```

But un-commentating `bindgen` in `Cargo.toml` does not work. It gives me following error:-

```
   Compiling bindgen_with_clang v0.1.0 (/home/smit/bindgen_with_clang)
error: failed to run custom build command for `bindgen_with_clang v0.1.0 (/home/smit/bindgen_with_clang)`

Caused by:
  process didn't exit successfully: `/home/smit/bindgen_with_clang/target/debug/build/bindgen_with_clang-b4cabdc5f6bc0d97/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'a `libclang` shared library is not loaded on this thread', /home/smit/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.1.1/src/lib.rs:1680:1
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by KyleMayes** [comment]
The issue is that when you add `bindgen` as a dependency it changes `clang-sys` (which `clang` also uses as a dependency for `libclang` function loading) to use the [`runtime` Cargo feature](https://github.com/KyleMayes/clang-sys#runtime). This feature requires explicitly loading an instanceof `libclang` at runtime. `clang` supports this, but only when its own `runtime` Cargo feature is enabled.

One option would be to enable the `runtime` feature for this crate:

```toml
[build-dependencies]
bindgen = "0.57.0"
clang = { version = "1.0.3", features = ["runtime"] }
```

Another would be to disable the `runtime` feature ([which is a default feature](https://github.com/rust-lang/rust-bindgen/blob/fb931bd6c1a91908fa34dab7bc76059f33131663/Cargo.toml#L74)) for the `bindgen` crate:

```toml
[build-dependencies]
bindgen = { version = "0.57.0", default-features = false }
clang = "1.0.3"
```

This crate requires that `clang-sys` have the same features enabled, not sure if there is a way to guarantee that or at least produce a better error message when other dependencies alter the `clang-sys` features.

**Comment by LastLightSith** [comment]
@KyleMayes Thanks. that solves the problem
